{
  description = "temple — renco's agent harness. an experiment in local AI. use at your own risk.";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];
    nixpkgsFor = forAllSystems (system: import nixpkgs {
      inherit system;
      config.allowUnfree = true;
    });
    lockFile = ./Cargo.lock;
  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgsFor.${system};

      # Single build — produces both binaries, compiles once.
      temple-all = pkgs.rustPlatform.buildRustPackage {
        pname = "temple";
        version = "0.1.0";
        src = pkgs.lib.cleanSource ./.;
        cargoLock = { inherit lockFile; };
        nativeBuildInputs = with pkgs; [ pkg-config ];
        buildInputs = with pkgs; [ openssl sqlite ];
        doCheck = false;

        # NOTE: completions are generated by running the built binaries,
        # so cross-compiled builds (e.g. aarch64 on x86_64) must disable
        # this. Oracle builds on-target (buildOnTarget = true).
        postInstall = ''
          mkdir -p $out/share/bash-completion/completions
          $out/bin/temple --generate-completions bash > $out/share/bash-completion/completions/temple
          $out/bin/temple-server --generate-completions bash > $out/share/bash-completion/completions/temple-server
          mkdir -p $out/share/zsh/site-functions
          $out/bin/temple --generate-completions zsh > $out/share/zsh/site-functions/_temple
          $out/bin/temple-server --generate-completions zsh > $out/share/zsh/site-functions/_temple-server
          mkdir -p $out/share/fish/vendor-completions
          $out/bin/temple --generate-completions fish > $out/share/fish/vendor-completions/temple.fish
          $out/bin/temple-server --generate-completions fish > $out/share/fish/vendor-completions/temple-server.fish
        '';

        meta = {
          description = "renco agent harness — server + TUI client";
          license = pkgs.lib.licenses.mit;
          mainProgram = "temple";
        };
      };
    in rec {
      temple = temple-all;
      temple-server = temple-all;
      default = temple-all;
    });

    devShells = forAllSystems (system: let
      pkgs = nixpkgsFor.${system};
    in {
      default = pkgs.mkShell {
        packages = with pkgs; [ cargo rustc rustfmt clippy gcc pkg-config openssl sqlite ];
        RUST_BACKTRACE = "1";
        PKG_CONFIG_PATH = with pkgs; lib.makeSearchPath "lib/pkgconfig" [
          openssl.dev
          sqlite.dev
        ];
      };
    });

    # NixOS module. The consuming flake passes pkgs; we inject our package.
    nixosModules.temple-server = { pkgs, ... }@args:
      import ./nix/module.nix (args // {
        templePackage = self.packages.${pkgs.system}.temple-server;
      });

    nixosModules.temple-daemon = { pkgs, ... }@args:
      import ./nix/daemon-module.nix (args // {
        templePackage = self.packages.${pkgs.system}.temple;
      });

    nixosModules.default = self.nixosModules.temple-server;
  };
}
