use std::sync::Arc;
use tokio::sync::Mutex;
use chrono::Datelike;

use crate::agent::Agent;
use crate::memory::Memory;
use crate::nextcloud::Nextcloud;
use crate::signal::Signal;

pub struct CronScheduler {
    agent: Arc<Agent>,
    memory: Arc<Memory>,
    signal: Arc<Signal>,
    nextcloud: Arc<Mutex<Nextcloud>>,
}

impl CronScheduler {
    pub fn new(
        agent: Arc<Agent>,
        memory: Arc<Memory>,
        signal: Arc<Signal>,
        nextcloud: Arc<Mutex<Nextcloud>>,
    ) -> Self {
        Self { agent, memory, signal, nextcloud }
    }

    /// Daily skills extraction: asks the model to review the day's
    /// conversations and distill reusable skills, then writes skills.md.
    pub async fn extract_skills(&self) -> Result<(), String> {
        tracing::info!("Running daily skills extraction...");

        // 1. Ask the model to extract skills from recent conversations
        self.extract_skills_from_conversations().await;

        // 2. Dump all skills (including new ones) to skills.md
        let skills = self.memory.get_all_skills().await
            .map_err(|e| format!("get skills: {e}"))?;

        let mut md = String::from(
            "# renco's learned skills\n\n\
             *Auto-generated by daily skills extraction. Do not edit manually.*\n\n",
        );

        for skill in &skills {
            md.push_str(&format!(
                "## {name}\n\n**Description:** {desc}\n\n\
                 **Pattern:**\n```\n{pattern}\n```\n\n\
                 **Used {freq} times{last}**\n\n",
                name = skill.name,
                desc = skill.description,
                pattern = skill.pattern,
                freq = skill.frequency,
                last = skill.last_used.map(|d| format!(", last {d}")).unwrap_or_default(),
            ));
        }

        if skills.is_empty() {
            md.push_str("_No skills extracted yet. Keep coding and they will appear._\n");
        }

        let path = dirs::data_dir()
            .unwrap_or_else(|| std::path::PathBuf::from("/var/lib/temple"))
            .join("temple/skills.md");
        if let Some(parent) = path.parent() {
            tokio::fs::create_dir_all(parent).await.ok();
        }
        tokio::fs::write(&path, &md)
            .await
            .map_err(|e| format!("write skills.md: {e}"))?;

        tracing::info!("Skills extraction complete — {} skills", skills.len());
        Ok(())
    }

    /// Ask the model to review recent conversations and extract reusable
    /// skills into the skills table.
    async fn extract_skills_from_conversations(&self) {
        let recent = match self.memory.get_recent_conversations(50).await {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!("Failed to get recent conversations: {e}");
                return;
            }
        };

        if recent.is_empty() {
            tracing::info!("No conversations to extract skills from");
            return;
        }

        let mut conv_summary = String::new();
        for entry in recent.iter().take(50) {
            conv_summary.push_str(&format!(
                "[{}] {}: {}\n",
                entry.timestamp.format("%m-%d %H:%M"),
                entry.role,
                &entry.content[..entry.content.len().min(300)]
            ));
        }

        let prompt = format!(
            "You are reviewing recent conversations between renco (an AI agent) and a user.\n\n\
             Review these conversations and extract any reusable skills — patterns, techniques,\n\
             or procedures that renco used successfully and should remember for future sessions.\n\n\
             For each skill, output a JSON object on its own line:\n\
             {{\"name\": \"short-name\", \"description\": \"what it does\", \"pattern\": \"the reusable pattern\"}}\n\n\
             Only extract genuinely reusable skills (not one-off actions). If there are none,\n\
             output nothing.\n\n\
             Conversations:\n{conv_summary}"
        );

        let req = crate::litellm::ChatRequest {
            model: self.agent.models.default_model.clone(),
            messages: vec![
                crate::litellm::ChatMessage::system(
                    "You are a skill extraction assistant. Output only JSON objects, one per line."
                ),
                crate::litellm::ChatMessage::user(&prompt),
            ],
            tools: None,
            stream: Some(false),
            stream_options: None,
            max_tokens: Some(2048),
            temperature: Some(0.3),
        };

        match self.agent.litellm.chat(req).await {
            Ok(resp) => {
                if let Some(choice) = resp.choices.first() {
                    if let Some(content) = choice.message.content.as_deref() {
                        let mut extracted = 0;
                        for line in content.lines() {
                            let line = line.trim();
                            if line.is_empty() || !line.starts_with('{') {
                                continue;
                            }
                            if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                                let name = v["name"].as_str().unwrap_or("").to_string();
                                let desc = v["description"].as_str().unwrap_or("").to_string();
                                let pattern = v["pattern"].as_str().unwrap_or("").to_string();
                                if name.is_empty() || desc.is_empty() {
                                    continue;
                                }
                                let skill = temple_protocol::Skill {
                                    name,
                                    description: desc,
                                    pattern,
                                    source_session: None,
                                    frequency: 1,
                                    last_used: Some(chrono::Utc::now()),
                                };
                                if let Err(e) = self.memory.upsert_skill(&skill).await {
                                    tracing::warn!("Failed to upsert skill: {e}");
                                } else {
                                    extracted += 1;
                                }
                            }
                        }
                        tracing::info!("Extracted {extracted} skills from conversations");
                    }
                }
            }
            Err(e) => {
                tracing::warn!("Skill extraction model call failed: {e}");
            }
        }
    }

    /// Daily nix flake update with llama.cpp regression checking.
    pub async fn smart_flake_update(&self) -> Result<(), String> {
        tracing::info!("Running smart flake update...");

        let flake_path = "/etc/nixos/flake.nix";
        if !tokio::fs::try_exists(flake_path).await.unwrap_or(false) {
            tracing::warn!("No flake at {flake_path}, skipping");
            return Ok(());
        }

        let lock_path = "/etc/nixos/flake.lock";
        let lock_content = tokio::fs::read_to_string(lock_path).await
            .map_err(|e| format!("read flake.lock: {e}"))?;
        let lock: serde_json::Value = serde_json::from_str(&lock_content)
            .map_err(|e| format!("parse flake.lock: {e}"))?;

        let llama_key = "llama-cpp";
        let current_rev = lock["nodes"][llama_key]["locked"]["rev"]
            .as_str()
            .unwrap_or("unknown")
            .to_string();

        tracing::info!("Current llama.cpp rev: {current_rev}");

        let output = tokio::process::Command::new("nix")
            .args(["flake", "update", "--flake", "/etc/nixos"])
            .output()
            .await
            .map_err(|e| format!("flake update spawn: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("flake update failed: {stderr}"));
        }

        let new_lock = tokio::fs::read_to_string(lock_path).await
            .map_err(|e| format!("read new flake.lock: {e}"))?;
        let new_lock: serde_json::Value = serde_json::from_str(&new_lock)
            .map_err(|e| format!("parse new flake.lock: {e}"))?;
        let new_rev = new_lock["nodes"][llama_key]["locked"]["rev"]
            .as_str()
            .unwrap_or("unknown")
            .to_string();

        tracing::info!("New llama.cpp rev: {new_rev}");

        if new_rev != "unknown" && current_rev != "unknown" && new_rev != current_rev {
            // Fetch commit list from GitHub API instead of needing a local checkout
            let url = format!(
                "https://api.github.com/repos/ggml-org/llama.cpp/compare/{current_rev}...{new_rev}"
            );
            let client = reqwest::Client::new();
            let resp = client
                .get(&url)
                .header("User-Agent", "temple-renco")
                .header("Accept", "application/vnd.github+json")
                .send()
                .await;

            let log = match resp {
                Ok(r) => r.text().await.unwrap_or_default(),
                Err(_) => String::new(),
            };

            let risk_keywords = [
                "regression", "breaking change", "incompatible", "segfault",
                "crash", "oom", "out of memory", "revert",
            ];
            let risk_count = risk_keywords
                .iter()
                .filter(|kw| log.to_lowercase().contains(*kw))
                .count();

            if risk_count > 2 {
                tracing::warn!(
                    "Risk detected in llama.cpp update ({risk_count} keywords) — reverting flake.lock"
                );
                let revert = tokio::process::Command::new("git")
                    .args(["-C", "/etc/nixos", "checkout", "--", "flake.lock"])
                    .output()
                    .await
                    .map_err(|e| format!("git revert: {e}"))?;
                if !revert.status.success() {
                    return Err("failed to revert flake.lock".into());
                }
                tracing::info!("Reverted flake.lock — kept llama.cpp at {current_rev}");
                self.signal
                    .notify(
                        "renco: flake update",
                        &format!("llama.cpp update skipped — {risk_count} risk keywords in {current_rev}..{new_rev}"),
                    )
                    .await
                    .ok();
            } else {
                tracing::info!("llama.cpp update looks safe ({risk_count} keywords)");
                self.signal
                    .notify(
                        "renco: flake update",
                        &format!("flake updated; llama.cpp {current_rev} → {new_rev}"),
                    )
                    .await
                    .ok();
            }
        }

        tracing::info!("Smart flake update complete");
        Ok(())
    }

    /// Weekly self-maintenance: update personality based on recent conversations.
    pub async fn self_maintenance(&self) -> Result<(), String> {
        tracing::info!("Running weekly self-maintenance (personality update)...");
        self.agent.update_personality().await;
        self.signal
            .notify(
                "renco: maintenance",
                "Weekly maintenance cycle completed — personality reviewed.",
            )
            .await?;
        Ok(())
    }

    pub async fn run_forever(&self) -> Result<(), String> {
        loop {
            let now = chrono::Utc::now();
            let hour = now.format("%H").to_string();
            let minute = now.format("%M").to_string();

            if hour == "03" && minute == "00" {
                if let Err(e) = self.extract_skills().await {
                    tracing::error!("skills extraction: {e}");
                }
                tokio::time::sleep(tokio::time::Duration::from_secs(61)).await;
            }

            if hour == "04" && minute == "00" {
                if let Err(e) = self.smart_flake_update().await {
                    tracing::error!("flake update: {e}");
                }
                tokio::time::sleep(tokio::time::Duration::from_secs(61)).await;
            }

            if now.weekday() == chrono::Weekday::Sun && hour == "05" && minute == "00" {
                if let Err(e) = self.self_maintenance().await {
                    tracing::error!("maintenance: {e}");
                }
                tokio::time::sleep(tokio::time::Duration::from_secs(61)).await;
            }

            tokio::time::sleep(tokio::time::Duration::from_secs(30)).await;
        }
    }
}
