use std::sync::Arc;
use tokio::sync::Mutex;
use chrono::Datelike;

use crate::agent::Agent;
use crate::memory::Memory;
use crate::ntfy::Ntfy;
use crate::nextcloud::Nextcloud;

pub struct CronScheduler {
    agent: Arc<Agent>,
    memory: Arc<Memory>,
    ntfy: Arc<Mutex<Ntfy>>,
    nextcloud: Arc<Mutex<Nextcloud>>,
}

impl CronScheduler {
    pub fn new(
        agent: Arc<Agent>,
        memory: Arc<Memory>,
        ntfy: Arc<Mutex<Ntfy>>,
        nextcloud: Arc<Mutex<Nextcloud>>,
    ) -> Self {
        Self { agent, memory, ntfy, nextcloud }
    }

    /// Daily skills extraction: asks the brain model to review the day's
    /// conversations and distill reusable skills.
    pub async fn extract_skills(&self) -> Result<(), String> {
        tracing::info!("Running daily skills extraction...");

        let skills = self.memory.get_all_skills().await
            .map_err(|e| format!("get skills: {e}"))?;

        let mut md = String::from(
            "# renco's learned skills\n\n\
             *Auto-generated by daily skills extraction. Do not edit manually.*\n\n",
        );

        for skill in &skills {
            md.push_str(&format!(
                "## {name}\n\n**Description:** {desc}\n\n\
                 **Pattern:**\n```\n{pattern}\n```\n\n\
                 **Used {freq} times{last}**\n\n",
                name = skill.name,
                desc = skill.description,
                pattern = skill.pattern,
                freq = skill.frequency,
                last = skill.last_used.map(|d| format!(", last {d}")).unwrap_or_default(),
            ));
        }

        if skills.is_empty() {
            md.push_str("_No skills extracted yet. Keep coding and they will appear._\n");
        }

        let path = dirs::data_dir()
            .unwrap_or_else(|| std::path::PathBuf::from("/var/lib/temple"))
            .join("temple/skills.md");
        if let Some(parent) = path.parent() {
            tokio::fs::create_dir_all(parent).await.ok();
        }
        tokio::fs::write(&path, &md)
            .await
            .map_err(|e| format!("write skills.md: {e}"))?;

        tracing::info!("Skills extraction complete — {} skills", skills.len());
        Ok(())
    }

    /// Daily nix flake update with llama.cpp regression checking.
    pub async fn smart_flake_update(&self) -> Result<(), String> {
        tracing::info!("Running smart flake update...");

        let flake_path = "/etc/nixos/flake.nix";
        if !tokio::fs::try_exists(flake_path).await.unwrap_or(false) {
            tracing::warn!("No flake at {flake_path}, skipping");
            return Ok(());
        }

        let lock_path = "/etc/nixos/flake.lock";
        let lock_content = tokio::fs::read_to_string(lock_path).await
            .map_err(|e| format!("read flake.lock: {e}"))?;
        let lock: serde_json::Value = serde_json::from_str(&lock_content)
            .map_err(|e| format!("parse flake.lock: {e}"))?;

        let llama_key = "llama-cpp";
        let current_rev = lock["nodes"][llama_key]["locked"]["rev"]
            .as_str()
            .unwrap_or("unknown")
            .to_string();

        tracing::info!("Current llama.cpp rev: {current_rev}");

        let output = tokio::process::Command::new("nix")
            .args(["flake", "update", "--flake", "/etc/nixos"])
            .output()
            .await
            .map_err(|e| format!("flake update spawn: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("flake update failed: {stderr}"));
        }

        let new_lock = tokio::fs::read_to_string(lock_path).await
            .map_err(|e| format!("read new flake.lock: {e}"))?;
        let new_lock: serde_json::Value = serde_json::from_str(&new_lock)
            .map_err(|e| format!("parse new flake.lock: {e}"))?;
        let new_rev = new_lock["nodes"][llama_key]["locked"]["rev"]
            .as_str()
            .unwrap_or("unknown")
            .to_string();

        tracing::info!("New llama.cpp rev: {new_rev}");

        if new_rev != "unknown" && current_rev != "unknown" && new_rev != current_rev {
            // Fetch commit list from GitHub API instead of needing a local checkout
            let url = format!(
                "https://api.github.com/repos/ggml-org/llama.cpp/compare/{current_rev}...{new_rev}"
            );
            let client = reqwest::Client::new();
            let resp = client
                .get(&url)
                .header("User-Agent", "temple-renco")
                .header("Accept", "application/vnd.github+json")
                .send()
                .await;

            let log = match resp {
                Ok(r) => r.text().await.unwrap_or_default(),
                Err(_) => String::new(),
            };

            let risk_keywords = [
                "regression", "breaking change", "incompatible", "segfault",
                "crash", "oom", "out of memory", "revert",
            ];
            let risk_count = risk_keywords
                .iter()
                .filter(|kw| log.to_lowercase().contains(*kw))
                .count();

            if risk_count > 2 {
                tracing::warn!(
                    "Risk detected in llama.cpp update ({risk_count} keywords) — reverting flake.lock"
                );
                let revert = tokio::process::Command::new("git")
                    .args(["-C", "/etc/nixos", "checkout", "--", "flake.lock"])
                    .output()
                    .await
                    .map_err(|e| format!("git revert: {e}"))?;
                if !revert.status.success() {
                    return Err("failed to revert flake.lock".into());
                }
                tracing::info!("Reverted flake.lock — kept llama.cpp at {current_rev}");

                self.ntfy.lock().await
                    .notify("renco: flake update",
                        &format!("llama.cpp update skipped — {risk_count} risk keywords in {current_rev}..{new_rev}"))
                    .await
                    .ok();
            } else {
                tracing::info!("llama.cpp update looks safe ({risk_count} keywords)");
                self.ntfy.lock().await
                    .notify("renco: flake update",
                        &format!("flake updated; llama.cpp {current_rev} → {new_rev}"))
                    .await
                    .ok();
            }
        }

        tracing::info!("Smart flake update complete");
        Ok(())
    }

    /// Weekly self-maintenance: update personality based on recent conversations.
    pub async fn self_maintenance(&self) -> Result<(), String> {
        tracing::info!("Running weekly self-maintenance (personality update)...");
        self.agent.update_personality().await;
        self.ntfy.lock().await
            .notify("renco: maintenance", "Weekly maintenance cycle completed — personality reviewed.")
            .await?;
        Ok(())
    }

    pub async fn run_forever(&self) -> Result<(), String> {
        loop {
            let now = chrono::Utc::now();
            let hour = now.format("%H").to_string();
            let minute = now.format("%M").to_string();

            if hour == "03" && minute == "00" {
                if let Err(e) = self.extract_skills().await {
                    tracing::error!("skills extraction: {e}");
                }
                tokio::time::sleep(tokio::time::Duration::from_secs(61)).await;
            }

            if hour == "04" && minute == "00" {
                if let Err(e) = self.smart_flake_update().await {
                    tracing::error!("flake update: {e}");
                }
                tokio::time::sleep(tokio::time::Duration::from_secs(61)).await;
            }

            if now.weekday() == chrono::Weekday::Sun && hour == "05" && minute == "00" {
                if let Err(e) = self.self_maintenance().await {
                    tracing::error!("maintenance: {e}");
                }
                tokio::time::sleep(tokio::time::Duration::from_secs(61)).await;
            }

            tokio::time::sleep(tokio::time::Duration::from_secs(30)).await;
        }
    }
}
